baseurl = "/"
languageCode = "en-us"
title = "Dr. med. Klaus G. Jürgens"
canonifyUrls = "true"
theme="landing-page-hugo"
[params]
    description = ""
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:kljuergens@aol.com"
