baseurl = "/"
languageCode = "en-us"
title = "Dr. med. Klaus G. J체rgens"
canonifyUrls = "true"
theme="landing-page-hugo"
[params]
    description = "Facharzt f체r Orthop채die, Chirotherapie und Sportorthop채die"
    custom_css = ["css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:kljuergens@aol.com"
